# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty


# Setup
title:            Swissbib
tagline:          'National Licences'
description:      'National Licences'
url:              http://swissbib.github.io/metadataNationalLicencesDocumentation/
baseurl:          /

author:
  name:           'Lionel Walter'
  url:            https://twitter.com/liowalter

exclude: [deploy.sh, files.txt, deploy-last-commit.sh, passwords.sh, tables]
