# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty


# Setup
title:            National Licences
tagline:          'Metadata Management & User Authentication'
description:      'Metadata Management & User Authentication'
url:              http://swissbib.github.io/metadataNationalLicencesDocumentation/
baseurl:          /

author:
  name:           'Lionel Walter'
  url:            https://twitter.com/liowalter

exclude: [deploy.sh, files.txt, deploy-last-commit.sh, passwords.sh, tables]

kramdown:
  toc_levels:     2..3
